update

diff --git a/.github/workflows/contrib-tests.yml b/.github/workflows/contrib-tests.yml
--- a/.github/workflows/contrib-tests.yml
+++ b/.github/workflows/contrib-tests.yml
@@ -54,10 +54,10 @@ jobs:
         if: ${{ always() }}
         run: |
           set -e
-          trap 'echo "::set-output name=result::failure"' ERR
+          trap echo "result=failure" >> $GITHUB_OUTPUT ERR
           pip install -e .[mathchat]
           pip uninstall -y openai
-          echo "::set-output name=result::success"
+          echo "result=failure" >> $GITHUB_OUTPUT
       - name: test MathChat
         if: ${{ steps.install_mathchat.outputs.result == 'success' }}
         run: |
