update

diff --git a/.github/workflows/contrib-openai.yml b/.github/workflows/contrib-openai.yml
--- a/.github/workflows/contrib-openai.yml
+++ b/.github/workflows/contrib-openai.yml
@@ -57,11 +57,10 @@ jobs:
         if: ${{ always() }}
         run: |
           set -e
-          trap 'echo "::set-output name=result::failure"' ERR
+          trap 'echo "result=failure" >> $GITHUB_OUTPUT' ERR
           pip install docker
           pip install -e .[mathchat]
-          echo "::set-output name=result::success"
-
+          echo "result=failure" >> $GITHUB_OUTPUT
       - name: Coverage MathChat
         if: ${{ steps.install_mathchat.outputs.result == 'success' }}
         env:
diff --git a/.github/workflows/contrib-tests.yml b/.github/workflows/contrib-tests.yml
--- a/.github/workflows/contrib-tests.yml
+++ b/.github/workflows/contrib-tests.yml
@@ -54,7 +54,7 @@ jobs:
         if: ${{ always() }}
         run: |
           set -e
-          trap echo "result=failure" >> $GITHUB_OUTPUT ERR
+          trap 'echo "result=failure" >> $GITHUB_OUTPUT' ERR
           pip install -e .[mathchat]
           pip uninstall -y openai
           echo "result=failure" >> $GITHUB_OUTPUT
